name: CICD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build: #Build Job#
    runs-on: ubuntu-latest
        
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Run build
        run: | 
          npm ci;
          npm run build;

  deploy: #Deploy Job#
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
      
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - name: Run deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: | 
          git config user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config user.name "${{ secrets.GIT_USER_NAME }}"
          npm ci;
          npm run predeploy;
          npx gh-pages -d dist -t true -b gh-pages -r https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git